#!/bin/bash

# NeuronSeqSampler - Large Value Display Demo
# This script demonstrates the enlarged BPM and rhythmogram scale value displays

echo "🔢 NeuronSeqSampler - Large Value Display Demo"
echo "=============================================="
echo ""
echo "ENHANCED FEATURE: Large BPM & Rhythmogram Scale Value Displays"
echo "• Value displays enlarged from 30x20px to 60x30px (2x wider, 1.5x taller)"
echo "• Text size increased from 9pt to 13pt (+44% larger text)"
echo "• Optimized sizing prevents scrolling handles on 3-digit BPM values"
echo ""
echo "USAGE INSTRUCTIONS:"
echo "1. Open the connection matrix (press 'M' if not visible)"
echo "2. Look at the right side for the dual vertical sliders"
echo "3. Left slider: Rhythmogram Scale (0.0-20.0, red thumb)"
echo "4. Right slider: BPM (30-260, green thumb)"
echo "5. Both sliders now span almost the full height of the panel"
echo ""
echo "VALUE DISPLAY LAYOUT:"
echo "┌─────────────────────────────────┐"
echo "│ Scale        BPM     │"
echo "│   │           │      │"
echo "│   │    20.0   │ 260  │  ← Slider tops"
echo "│   │           │      │"
echo "│   │    10.0   │ 150  │  ← Middle" 
echo "│   │           │      │"
echo "│   │     0.0   │  30  │  ← Slider bottoms"
echo "│                     │"
echo "│ ┏━━━━━━━┓ ┏━━━━━━━┓ │  ← LARGE value displays"
echo "│ ┃  5.0  ┃ ┃ 120.0 ┃ │    (60x30px, 13pt text)"  
echo "│ ┗━━━━━━━┛ ┗━━━━━━━┛ │"
echo "│     [Autodetect]     │  ← Toggle button"
echo "└─────────────────────────────────┘"
echo ""
echo "ADVANTAGES:"
echo "• Wider displays accommodate 3-digit BPM values (120.0-260.0)"  
echo "• Larger text size for better readability (+44% bigger text)"
echo "• No scrolling handles - proper sizing for all value ranges"
echo "• Centered positioning under sliders for visual clarity"
echo "• Professional appearance with consistent sizing"
echo ""
echo "TESTING TIPS:"
echo "• Drag sliders and watch the large value displays update in real-time"
echo "• Notice how easy it is to read exact parameter values"
echo "• Test autodetect toggle - BPM display shows 🎵 when active"
echo "• Compare old small display vs new large display readability"
echo ""

# Start the application
echo "Starting NeuronSeqSampler with large value displays..."
echo "Press 'M' to show/hide the connection matrix if needed"
echo ""

./NeuronSeqSampler --testing