#!/bin/bash

# Demo script for testing the new BPM slider feature

echo "🎵 BPM Slider Demo - Tempo-Relative Rhythmogram Frequencies"
echo "==========================================================="
echo ""
echo "New BPM feature added:"
echo "• Vertical BPM slider (30.0-260.0 BPM, default 120.0)"
echo "• Real-time BPM value display"  
echo "• Tempo-relative frequency scaling of Todd (1994) rhythmogram bands"
echo "• Positioned next to the Scale slider at right edge of matrix"
echo "• 0.1 step precision for fine tempo control"
echo ""
echo "How tempo scaling works:"
echo "• At 120 BPM (default): frequencies match Todd's original scale"
echo "  - 0.125Hz = 8-beat phrases"
echo "  - 1.0Hz = quarter note level"
echo "  - 4.0Hz = sixteenth note subdivisions" 
echo ""
echo "• At 60 BPM (half tempo): all frequencies scaled down by 0.5x"
echo "  - 0.0625Hz = 8-beat phrases (slower)"
echo "  - 0.5Hz = quarter note level (slower)"
echo "  - 2.0Hz = sixteenth note subdivisions (slower)"
echo ""
echo "• At 240 BPM (double tempo): all frequencies scaled up by 2.0x"
echo "  - 0.25Hz = 8-beat phrases (faster)"
echo "  - 2.0Hz = quarter note level (faster)" 
echo "  - 8.0Hz = sixteenth note subdivisions (faster)"
echo ""
echo "Usage instructions:"
echo "1. Launch the application"
echo "2. Press 'M' to open the rhythmogram connection matrix"
echo "3. Press 'R' to enable rhythmogram analysis"
echo "4. Press spacebar to generate audio for analysis"
echo "5. Look for both 'Scale' and 'BPM' sliders at the right edge"
echo "6. Adjust BPM slider to change tempo (30-260 BPM)"
echo "7. Watch how filter frequencies adapt to the new tempo"
echo "8. Observe different rhythmic responses at different tempos"
echo ""
echo "Technical details:"
echo "• Scaling formula: frequency = default_frequency × (bpm / 120.0)"
echo "• Bandwidth scales proportionally with frequency"
echo "• Resonance (Q factor) remains constant across tempos"
echo "• Real-time filter bank updates when BPM changes"
echo ""

# Launch the application for testing
echo "Launching NeuronSeqSampler in testing mode..."
echo "Look for the new BPM slider next to the Scale slider!"
echo ""
./NeuronSeqSampler --testing