#!/bin/bash

echo "Testing Filter Resonance Controls"
echo "================================="
echo ""
echo "NEW FILTER RESONANCE SYSTEM:"
echo "📊 8 Filter Bands with Individual Resonance Control"
echo "🎛️ Q Factor Range: 0.1 to 10.0"
echo "🔊 Default Resonance Values Per Band:"
echo "   - 1.0 Hz (Ultra-low): Q = 2.0 (moderate)"
echo "   - 3.36 Hz (Very low): Q = 2.5 (slightly higher)"
echo "   - 11.3 Hz (Low): Q = 3.0 (medium)"
echo "   - 38.0 Hz (Sub bass): Q = 4.0 (punchy)"
echo "   - 127.8 Hz (Bass): Q = 5.0 (tight)"
echo "   - 429.7 Hz (Mids): Q = 3.5 (clear)"
echo "   - 1445.7 Hz (Presence): Q = 2.5 (smooth)"
echo "   - 8000.0 Hz (Air): Q = 1.5 (gentle)"
echo ""
echo "GUI LAYOUT:"
echo "✅ Gain Sliders: Left side (0.0x - 2.0x) - Green"
echo "✅ Resonance Sliders: Right side (Q 0.1 - 10.0) - Blue"
echo "✅ Real-time Control: Instant filter response"
echo "✅ Per-band Tuning: Independent Q control"
echo ""
echo "FILTER EFFECTS:"
echo "🔹 Low Q (0.1-1.0): Gentle, smooth filtering"
echo "🔹 Medium Q (1.0-5.0): Balanced response"
echo "🔹 High Q (5.0-10.0): Sharp, resonant peaks"
echo ""
echo "TO TEST:"
echo "1. Toggle matrix visibility with 'M' key"
echo "2. Adjust blue resonance sliders next to gain controls"
echo "3. Listen to filter character changes in real-time"
echo "4. Try different Q values for each frequency band"
echo ""
echo "Starting application..."
echo ""
sleep 3

cd /home/jaakko/Asiakirjat/Koodii/neuronSeqSampler
./NeuronSeqSampler --testing