#!/bin/bash

echo "🎵 Practical Quantization Preset Test"
echo "======================================"
echo ""
echo "This script tests quantization preset loading in the actual application."
echo ""
echo "📋 Test Instructions:"
echo "1. Build and run the neuronSeqSampler"
echo "2. Go to menu: Presets → Load Preset"
echo "3. Load 'Factory Drum Pattern' preset"
echo "4. Press 'Q' to toggle quantization visibility"
echo "5. Verify quantization settings match preset:"
echo "   • Enabled: ✓ (checked)"
echo "   • Grid: 1/16 Note"
echo "   • Amount: 80%"
echo "   • Swing: 20%"
echo ""
echo "6. Load 'Ambient Textures' preset"
echo "7. Verify quantization settings:"
echo "   • Enabled: ✗ (unchecked)"
echo "   • Grid: 1/2 Note"
echo "   • Amount: 0%"
echo "   • Swing: 0%"
echo ""
echo "🔨 Building the application now..."

# Build the project
make clean && make

if [ $? -eq 0 ]; then
    echo ""
    echo "✅ Build successful!"
    echo ""
    echo "🚀 You can now run: ./neuronSeqSampler"
    echo ""
    echo "📝 Quantization Preset Test Checklist:"
    echo "□ Load 'Factory Drum Pattern' preset"
    echo "□ Press 'Q' to show quantization panel"
    echo "□ Verify: Enabled=ON, Grid=1/16, Amount=80%, Swing=20%"
    echo "□ Load 'Ambient Textures' preset"
    echo "□ Verify: Enabled=OFF, Grid=1/2, Amount=0%, Swing=0%"
    echo "□ Load 'Test' preset"
    echo "□ Verify: Enabled=ON, Grid=1/8, Amount=100%, Swing=0%"
    echo ""
    echo "🎯 Expected behavior:"
    echo "• Quantization settings should change when loading different presets"
    echo "• GUI controls should update to match loaded preset values"
    echo "• Enabling/disabling quantization should affect audio timing"
    echo ""
    echo "💾 Preset details:"
    echo ""
    echo "🥁 Factory Drum Pattern:"
    echo "   └─ Quantization: ON, 1/16 notes, 80% strength, 20% swing"
    echo ""
    echo "🌊 Ambient Textures:"
    echo "   └─ Quantization: OFF (for free-flowing ambient sounds)"
    echo ""
    echo "🧪 Test:"
    echo "   └─ Quantization: ON, 1/8 notes, 100% strength, straight timing"
else
    echo ""
    echo "❌ Build failed! Please check for compilation errors."
    exit 1
fi