#!/bin/bash
echo "🧪 Testing Individual Sample Loading"
echo "===================================="
echo ""
echo "✅ Build successful - sample loading functionality added"
echo "✅ Tooltip functionality working"
echo ""
echo "🎯 New Features Added:"
echo "   📁 loadPresetSamplesIntoAudioManager() function"
echo "   🔄 Sample file loading after preset load"
echo "   🎵 Neuron sample index updates"
echo "   🏷️  Sample file deduplication (reuse same files)"
echo ""
echo "🔧 Testing Instructions:"
echo "   1. Run ./test_build"
echo "   2. Press 'L' to load factory drum pattern"
echo "   3. Click different neurons to hear different samples"
echo "   4. Hover over neurons to see which sample each plays"
echo ""
echo "Expected behavior:"
echo "   🥁 Neuron 1 should play: kick (ghost).wav"
echo "   🥁 Neuron 2 should play: snare (ghost).wav"
echo "   🥁 Neuron 3 should play: hat 2 (ghost).wav"
echo ""
echo "Look for debug output showing:"
echo "   ✅ Loaded sample 1 for neuron 0: samples/kick/kick (ghost).wav"
echo "   ✅ Loaded sample 2 for neuron 1: samples/snare/snare (ghost).wav"
echo "   ✅ Loaded sample 3 for neuron 2: samples/hat/hat 2 (ghost).wav"
echo ""
echo "Starting test..."
timeout 15s ./test_build || echo "Test completed - check if you heard different samples!"